# Generated by Django 2.2.11 on 2020-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=512)),
                ('number_of_goods', models.IntegerField()),
                ('photo', models.CharField(max_length=1024)),
            ],
        ),
    ]
